apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oulad
resources:
  - ../../base
  - mlflow.yaml
  - pipeline-cronjob.yaml
images:
  - name: oulad-api
    newName: ghcr.io/jasleenminhas578/oulad-api
    newTag: latest
  - name: oulad-pipeline
    newName: ghcr.io/jasleenminhas578/oulad-pipeline
    newTag: latest
  - name: oulad-mlflow
    newName: ghcr.io/jasleenminhas578/oulad-mlflow
    newTag: latest
configMapGenerator:
  - name: oulad-config
    behavior: merge
    literals:
      - MODEL_URI=s3://oulad-mlops-jasleenminhas578-22230/models/champion
      - DATA_URI=s3://oulad-mlops-jasleenminhas578-22230/data
      - MODELS_URI=s3://oulad-mlops-jasleenminhas578-22230/models
      - MLFLOW_TRACKING_URI=http://oulad-mlflow:5000
      - AWS_DEFAULT_REGION=ca-central-1
      - GITHUB_REPO=jasleenminhas578/oulad-mlops
      - INJECT_DRIFT_AT=5
  - name: mlflow-config
    literals:
      - MLFLOW_ARTIFACTS_DESTINATION=s3://oulad-mlops-jasleenminhas578-22230/mlflow
      - AWS_DEFAULT_REGION=ca-central-1
