apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oulad
resources:
  - namespace.yaml
  - api.yaml
configMapGenerator:
  - name: oulad-config
    literals:
      - MODEL_URI=artifacts/models/champion
